KNOWN_INSTITUTIONS = [
    "Abia State University",
    "Abubakar Tafawa Balewa University",
    "Adekunle Ajasin University",
    "Afe Babalola University",
    "Ahmadu Bello University",
    "Ajayi Crowther University",
    "American University of Nigeria",
    "Babcock University",
    "Bayero University Kano",
    "Benson Idahosa University",
    "Benue State University",
    "Bowen University",
    "Covenant University",
    "Delta State University",
    "Ekiti State University",
    "Federal University of Technology Akure",
    "Federal University of Technology Minna",
    "Federal University of Technology Owerri",
    "Igbinedion University",
    "Kaduna State University",
    "Kogi State University",
    "Lagos State University",
    "Lead City University",
    "Madonna University",
    "Nile University of Nigeria",
    "Nnamdi Azikiwe University",
    "Obafemi Awolowo University",
    "Pan Atlantic University",
    "Rivers State University",
    "University of Abuja",
    "University of Benin",
    "University of Calabar",
    "University of Ibadan",
    "University of Ilorin",
    "University of Jos",
    "University of Lagos",
    "University of Maiduguri",
    "University of Nigeria Nsukka",
    "University of Port Harcourt",
    "University of Uyo",
]

INSTITUTION_ALIASES = {
    "UNN": "University of Nigeria Nsukka",
    "UNILAG": "University of Lagos",
    "UI": "University of Ibadan",
    "ABU": "Ahmadu Bello University",
    "OAU": "Obafemi Awolowo University",
    "FUTA": "Federal University of Technology Akure",
    "FUTO": "Federal University of Technology Owerri",
}
